/* oxlint-disable react/only-export-components */
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { supabase } from '../lib/supabase'
import { AuthoritativeFields, parsePickupState, type PickupItem } from './PickupWorkspace'

type Json=Record<string,unknown>
const object=(value:unknown):Json|null=>typeof value==='object'&&value!==null&&!Array.isArray(value)?value as Json:null
const optional=(value:string)=>value.trim()||null
const displayDate=(value:string)=>value?new Date(value).toLocaleString():'—'
const money=(value:string|null)=>value===null?'Not configured':`$${value}`
export const isoToDatetimeLocal=(value:string):string=>{const date=new Date(value);if(Number.isNaN(date.getTime()))return'';const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,23)}
const editError=(message:string)=>{const value=message.toLowerCase();if(value.includes('not found')||value.includes('not eligible')||value.includes('pricing started')||value.includes('continuity')||value.includes('billing'))return'Authoritative state changed and this Reservation is no longer editable. Refresh Reservations.';if(value.includes('aal2')||value.includes('permission')||value.includes('application user'))return'Authorization/security: an active authorized user with AAL2 is required.';if(value.includes('after'))return'Validation: scheduled return must be after scheduled start.';return'Edit Reservation could not be completed. Refresh authoritative state and try again.'}

export function EditReservationWorkspace({onError,initialReservationId=null,onInitialReservationHandled=()=>{}}:{onError:(value:string|null)=>void;initialReservationId?:string|null;onInitialReservationHandled?:()=>void}){
 const[items,setItems]=useState<PickupItem[]>([]),[loading,setLoading]=useState(true),[authoritativeLoadVersion,setAuthoritativeLoadVersion]=useState(0),[busy,setBusy]=useState(false),[reservationId,setReservationId]=useState(''),[start,setStart]=useState(''),[expectedReturn,setExpectedReturn]=useState(''),[originalStart,setOriginalStart]=useState(''),[originalExpectedReturn,setOriginalExpectedReturn]=useState(''),[startChanged,setStartChanged]=useState(false),[expectedReturnChanged,setExpectedReturnChanged]=useState(false),[advisor,setAdvisor]=useState(''),[roNumber,setRoNumber]=useState(''),[notes,setNotes]=useState(''),[result,setResult]=useState<Json|null>(null),handledInitialReservationId=useRef<string|null>(null)
 const populate=(item:PickupItem|null)=>{setStart(item?isoToDatetimeLocal(item.start):'');setExpectedReturn(item?isoToDatetimeLocal(item.expectedReturn):'');setOriginalStart(item?.start??'');setOriginalExpectedReturn(item?.expectedReturn??'');setStartChanged(false);setExpectedReturnChanged(false);setAdvisor(item?.serviceAdvisor??'');setRoNumber(item?.roNumber??'');setNotes(item?.notes??'')}
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.rpc('get_pricing_agreement_pickup_state',{p_reference_at:new Date().toISOString()});if(error){onError(editError(error.message));setLoading(false);return null}try{const loaded=parsePickupState(data);setItems(loaded);setAuthoritativeLoadVersion(version=>version+1);onError(null);setLoading(false);return loaded}catch{onError('Unexpected failure: Supabase returned an unrecognized Reservation response.');setLoading(false);return null}},[onError])
 useEffect(()=>{void load()},[load]);const selected=items.find(item=>item.reservationId===reservationId)??null
 useEffect(()=>{if(!authoritativeLoadVersion||loading||!initialReservationId||handledInitialReservationId.current===initialReservationId)return;handledInitialReservationId.current=initialReservationId;const authoritativeItem=items.find(item=>item.reservationId===initialReservationId)??null;if(authoritativeItem){setReservationId(authoritativeItem.reservationId);populate(authoritativeItem);onError(null)}else{setReservationId('');populate(null);onError('Authoritative state changed: the requested Reservation is not available to edit. Refresh Edit Reservation before continuing.')}onInitialReservationHandled()},[authoritativeLoadVersion,initialReservationId,items,loading,onError,onInitialReservationHandled])
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!selected)return onError('Validation: select a Reservation.');const submittedStart=startChanged?new Date(start).toISOString():originalStart,submittedReturn=expectedReturnChanged?new Date(expectedReturn).toISOString():originalExpectedReturn;if(!submittedStart||!submittedReturn||new Date(submittedReturn).getTime()<=new Date(submittedStart).getTime())return onError('Validation: scheduled return must be after scheduled start.');setBusy(true);onError(null);const{data,error}=await supabase.rpc('update_precheckin_reservation_state',{p_reservation_id:selected.reservationId,p_start_date:submittedStart,p_expected_return_datetime:submittedReturn,p_service_advisor:optional(advisor),p_ro_number:optional(roNumber),p_notes:optional(notes)});if(error)onError(editError(error.message));else{const payload=object(data);if(!payload)onError('Unexpected failure: Supabase returned an unrecognized edit result.');else{const loaded=await load();if(loaded){populate(loaded.find(item=>item.reservationId===selected.reservationId)??null);setResult(payload)}else onError('State sync failed after the edit. Refresh Reservations before continuing.')}}setBusy(false)}
 if(result){const reservation=object(result.reservation),transportationEvent=object(result.transportation_event);return <section className="reservation-success"><p className="eyebrow">AUTHORITATIVE EDIT RESULT</p><h2>Reservation edit complete</h2><p>Exact authoritative result returned by Supabase.</p><AuthoritativeFields value={result}/>{reservation&&<><h3>Authoritative Reservation</h3><AuthoritativeFields value={reservation}/></>}{transportationEvent&&<><h3>Authoritative Transportation Event</h3><AuthoritativeFields value={transportationEvent}/></>}<button className="primary-action" type="button" onClick={()=>setResult(null)}>Return to Edit Reservation</button></section>}
 if(loading)return <section className="reservation-card">Loading authoritative editable Reservations…</section>
 return <section className="pickup-workspace"><div className="reservation-card"><div className="section-heading"><div><h2>Edit Reservation</h2><p>Changing scheduled start changes the reserved and billing start used at later pickup. Actual physical handoff remains a Check-in / Pickup fact.</p><p>Editing does not assign a VIN or start vehicle use, a pricing timer, or billing.</p></div><button type="button" onClick={()=>{setReservationId('');populate(null);void load()}}>Refresh</button></div><label>Reservation<select value={reservationId} onChange={event=>{const id=event.target.value;setReservationId(id);populate(items.find(item=>item.reservationId===id)??null)}}><option value="">Select a pre-check-in Reservation</option>{items.map(item=><option value={item.reservationId} key={item.reservationId}>{item.customerName||'Customer'} · {item.vehicleModel} · {displayDate(item.start)}</option>)}</select></label></div>{selected&&<><article className="reservation-card pickup-detail"><h3>Read-only Reservation context</h3><dl><div><dt>Customer</dt><dd>{selected.customerName}</dd></div><div><dt>Reservation type</dt><dd>{selected.reservationType}</dd></div><div><dt>Vehicle model</dt><dd>{selected.vehicleModel}</dd></div><div><dt>Pay type</dt><dd>{selected.payType}</dd></div><div><dt>Initial / current rate plan</dt><dd>{selected.initialPlan} / {selected.currentPlan}</dd></div><div><dt>Pricing snapshots</dt><dd>Daily {money(selected.daily)} · Weekly {money(selected.weekly)} · Monthly {money(selected.monthly)}</dd></div><div><dt>Reservation ID</dt><dd>{selected.reservationId}</dd></div><div><dt>Transportation Event ID</dt><dd>{selected.eventId}</dd></div><div><dt>Pricing agreement ID</dt><dd>{selected.agreementId}</dd></div></dl></article><form className="reservation-card reservation-form" onSubmit={submit}><label>Scheduled start<input required type="datetime-local" step="0.001" value={start} onChange={event=>{setStart(event.target.value);setStartChanged(true)}}/></label><label>Scheduled return<input required type="datetime-local" step="0.001" value={expectedReturn} onChange={event=>{setExpectedReturn(event.target.value);setExpectedReturnChanged(true)}}/></label><label>Service advisor<input value={advisor} onChange={event=>setAdvisor(event.target.value)}/></label><label>RO number<input value={roNumber} onChange={event=>setRoNumber(event.target.value)}/></label><label className="wide">Notes<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><div className="form-actions wide"><button className="primary-action" disabled={busy}>{busy?'Saving…':'Save Reservation changes'}</button></div></form></>}</section>
}
