import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type ImpactItem={id:string;customerName:string;vehicleClass:string;start:string;end:string;status:string;dates:string[];kind:'Reservation'|'Quote'}
type Impact={hardReservations:ImpactItem[];atRiskQuotes:ImpactItem[]}
type ModelCapacity={vehicleClass:string;dailyLimit:number|null;configured:boolean;hasActiveRateCard:boolean;impact:Impact}
const record=(value:unknown):Record<string,unknown>|null=>typeof value==='object'&&value!==null&&!Array.isArray(value)?value as Record<string,unknown>:null
const strings=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[]
const parseItems=(value:unknown,kind:ImpactItem['kind']):ImpactItem[]=>Array.isArray(value)?value.map(record).filter(Boolean).map(item=>({
  id:String(item![kind==='Reservation'?'reservation_id':'quote_id']??''),customerName:typeof item!.customer_name==='string'?item!.customer_name:'Customer unavailable',
  vehicleClass:String(item!.vehicle_class??''),start:String(item!.start_date??''),end:String(item!.expected_return_datetime??''),status:String(item!.status??''),
  dates:strings(item![kind==='Reservation'?'conflict_dates':'risk_dates']),kind,
})).filter(item=>item.id):[]
const parseImpact=(value:unknown):Impact=>{const item=record(value);return {hardReservations:parseItems(item?.hard_reservation_conflicts,'Reservation'),atRiskQuotes:parseItems(item?.at_risk_quotes,'Quote')}}

export function ReservationCapacityManagement({onBack}:{onBack:()=>void}){
  const [models,setModels]=useState<ModelCapacity[]>([]);const [drafts,setDrafts]=useState<Record<string,string>>({});const [newModel,setNewModel]=useState('');const [newCapacity,setNewCapacity]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null)
  const load=useCallback(async()=>{setBusy(true);setMessage(null);const result=await supabase.rpc('get_admin_rental_reservation_capacity_state');const root=record(result.data)
    if(result.error||root?.status!=='admin_rental_reservation_capacity_ready'||!Array.isArray(root.models)){setMessage('Reservation Capacity configuration could not be loaded.');setBusy(false);return}
    const parsed=root.models.map(record).filter(Boolean).map(item=>({vehicleClass:typeof item!.vehicle_class==='string'?item!.vehicle_class:'',dailyLimit:typeof item!.daily_limit==='number'?item!.daily_limit:null,configured:item!.configured===true,hasActiveRateCard:item!.has_active_rate_card===true,impact:parseImpact(item!.impact)})).filter(item=>item.vehicleClass)
    setModels(parsed);setDrafts(Object.fromEntries(parsed.map(item=>[item.vehicleClass,item.dailyLimit===null?'':String(item.dailyLimit)])));setBusy(false)
  },[])
  useEffect(()=>{void load()},[load])
  const saveCapacity=async(vehicleClass:string,value:string)=>{if(!vehicleClass.trim()){setMessage('Rental model/class is required.');return false}if(!/^\d+$/.test(value)){setMessage('Reservation Capacity must be a whole number zero or greater.');return false}setBusy(true);setMessage(null);const result=await supabase.rpc('upsert_admin_rental_reservation_capacity_state',{p_vehicle_class:vehicleClass.trim(),p_daily_limit:Number(value)});if(result.error){setMessage('Reservation Capacity could not be saved.');setBusy(false);return false}await load();return true}
  const add=async()=>{if(await saveCapacity(newModel,newCapacity)){setNewModel('');setNewCapacity('')}}
  const remove=async(item:ModelCapacity)=>{setBusy(true);setMessage(null);const result=await supabase.rpc('remove_admin_rental_reservation_capacity_state',{p_vehicle_class:item.vehicleClass});if(result.error)setMessage('Reservation Capacity configuration could not be removed.');else await load();setBusy(false)}
  const warnings=models.flatMap(item=>[...item.impact.hardReservations,...item.impact.atRiskQuotes])
  const warningList=(items:ImpactItem[])=><ul>{items.map(item=><li key={`${item.kind}-${item.id}`}><strong>{item.customerName}</strong> — {item.kind} <code>{item.id}</code>, {item.vehicleClass}, {item.start} to {item.end}, status {item.status}. Affected local dates: {item.dates.join(', ')}</li>)}</ul>
  return <main className="content"><section className="page-heading"><div><p className="eyebrow">ADMIN / RENTAL</p><h1>Reservation Capacity</h1><p>Configure fixed model-level capacity. Missing configuration is unavailable; no defaults are invented.</p></div><div className="page-actions"><button type="button" onClick={onBack}>Back to Admin Console</button><button type="button" onClick={()=>void load()} disabled={busy}>Refresh</button></div></section>
    {message&&<div className="data-message error-message" role="alert">{message}</div>}
    <section className="vehicle-table-card"><h2>Add Model Capacity</h2><p>A capacity-only model cannot be offered for a Quote or Reservation until active Rental pricing exists.</p><div className="inline-form"><label>Rental model/class<input value={newModel} onChange={event=>setNewModel(event.target.value)} /></label><label>Whole-number capacity<input inputMode="numeric" value={newCapacity} onChange={event=>setNewCapacity(event.target.value)} /></label><button type="button" disabled={busy} onClick={()=>void add()}>Add Model Capacity</button></div></section>
    <section className="vehicle-table-card"><div className="table-wrap"><table><thead><tr><th>Rental model/class</th><th>Current capacity</th><th>Pricing availability</th><th>Action</th></tr></thead><tbody>{models.map(item=><tr key={item.vehicleClass}><td><strong>{item.vehicleClass}</strong></td><td><input aria-label={`${item.vehicleClass} daily Reservation Capacity`} inputMode="numeric" value={drafts[item.vehicleClass]??''} placeholder="Not configured" onChange={event=>setDrafts(current=>({...current,[item.vehicleClass]:event.target.value}))}/><div>{item.configured?`Configured: ${item.dailyLimit}`:'Not configured (fail-closed)'}</div></td><td>{item.hasActiveRateCard?'Active Rental rate card':'No active Rental rate card — capacity-only model'}</td><td><button type="button" disabled={busy} onClick={()=>void saveCapacity(item.vehicleClass,drafts[item.vehicleClass]??'')}>Save</button>{item.configured&&<button type="button" disabled={busy} onClick={()=>void remove(item)}>Remove</button>}</td></tr>)}</tbody></table></div>{!busy&&models.length===0&&<p className="empty-state">No configured capacity or active Rental rate-card models.</p>}</section>
    {warnings.length>0&&<section className="vehicle-table-card" aria-live="polite"><h2>Future capacity impact</h2>{models.map(item=>item.impact.hardReservations.length>0&&<div key={`hard-${item.vehicleClass}`}><h3>Hard Reservation conflicts — {item.vehicleClass}</h3><p>Committed Reservations exceed the saved capacity on one or more local dates. No Reservation has been selected for displacement.</p>{warningList(item.impact.hardReservations)}</div>)}{models.map(item=>item.impact.atRiskQuotes.length>0&&<div key={`quote-${item.vehicleClass}`}><h3>At-risk Quote pressure — {item.vehicleClass}</h3><p>Quotes are non-binding and do not consume committed capacity, but these active Quotes would exceed capacity if converted.</p>{warningList(item.impact.atRiskQuotes)}</div>)}</section>}
  </main>
}
