import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import './BillingWorkspace.css'

type Reservation = { reservation_id: string | null; status: string | null; reservation_type: string | null; requested_model: string | null; pay_type: string | null; start_date: string | null; expected_return_datetime: string | null; actual_return_datetime: string | null; billed_through_datetime: string | null }
type Customer = { customer_id: string | null; tekion_customer_number: string | null; name: string | null; phone: string | null; email: string | null }
type CurrentVehicle = { vehicle_event_id: string | null; vehicle_id: string | null; vin: string | null; vin_last8: string | null; stock_number: string | null; model_year: number | null; model: string | null; trim: string | null; fleet_type: string | null; current_tag: string | null; actual_out_at: string | null; actual_in_at: string | null; current_vehicle_contract_day: number | null }
type Segment = { billing_line_id: string; vehicle_id: string | null; vehicle_event_id: string | null; contract_period_id: string | null; pay_type_rule_id: string | null; pay_type: string | null; line_type: string; source_rule: string | null; start_time: string | null; end_time: string | null; paid_through_at: string | null; is_open: boolean; amount: string; tax_amount: string; tax_billing_line_id: string | null; tax_line_amount: string | null; daily_rate_override: string | null; default_daily_rate_snapshot: string | null; tax_rate_snapshot: string | null; is_taxable_snapshot: boolean | null; tax_rate_source_snapshot: string | null; warranty_provider_id: string | null; default_covered_days_snapshot: number | null; covered_days_override: number | null; extended_from_billing_line_id: string | null }
type ExtendedWarranty = { case_id: string; provider_id: string | null; provider_name: string | null; default_covered_days_snapshot: number | null; approved_days: number | null; effective_covered_days: number | null; default_daily_rate_snapshot: string | null; coverage_started_at: string | null; coverage_exhausted_at: string | null; current_contract_day: number | null; post_coverage_pay_type_rule_id: string | null; requires_manual_review: boolean; can_override: boolean }
type ReadyPreview = { status: 'billing_preview_ready'; transportation_event_id: string; transportation_event_status: string; reservation_id: string; reservation_status: string; reservation_type: string; customer: Customer; vehicle: Omit<CurrentVehicle, 'vehicle_event_id'|'actual_out_at'|'actual_in_at'|'current_vehicle_contract_day'>; vehicle_event_id: string; contract_period_id: string; vehicle_out_at: string; contract_out_at: string; expected_return_at: string | null; actual_return_at: string | null; billed_through_at: string | null; current_billing_line_id: string | null; line_type: string | null; pay_type_rule_id: string; pay_type: string; vehicle_class: string | null; billing_start: string; preview_end: string; effective_at: string; contract_days: number; daily_rate: string; rate_source: string; subtotal: string; is_taxable: boolean; tax_rate: string; tax_amount: string; tax_rate_source: string | null; tax_explanation: string | null; total: string; historical_subtotal: string; historical_tax: string; accumulated_subtotal: string; accumulated_tax: string; accumulated_total: string; segments: Segment[]; extended_warranty: ExtendedWarranty | null }
type AttentionPreview = { status: 'billing_preview_missing_dependency'|'billing_preview_missing_configuration'|'billing_preview_unavailable'; transportation_event_id: string; effective_at: string; missing_dependency?: string; missing_configuration?: string; [context: string]: unknown }
type WorkspaceItem = { transportation_event_id: string; transportation_event_status: string; source_type: string | null; source_id: string | null; expected_return_at: string | null; reservation: Reservation; customer: Customer; current_vehicle: CurrentVehicle; preview: ReadyPreview | AttentionPreview }
type Workspace = { status: 'billing_workspace_ready'; effective_at: string; case_count: number; ready_count: number; attention_count: number; accumulated_subtotal: string; accumulated_tax: string; accumulated_total: string; items: WorkspaceItem[] }

const isObject=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const isString=(v:unknown):v is string=>typeof v==='string'
const nullableString=(v:unknown)=>v===null||isString(v)
const nullableNumber=(v:unknown)=>v===null||(typeof v==='number'&&Number.isFinite(v))
const number=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)
const money=(v:unknown):v is string=>isString(v)&&/^-?(0|[1-9]\d*)(\.\d+)?$/.test(v)
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>k in v)
const strings=(o:Record<string,unknown>,keys:string[])=>keys.every(k=>isString(o[k]))
const nullableStrings=(o:Record<string,unknown>,keys:string[])=>keys.every(k=>nullableString(o[k]))

const segmentKeys=['billing_line_id','vehicle_id','vehicle_event_id','contract_period_id','pay_type_rule_id','pay_type','line_type','source_rule','start_time','end_time','paid_through_at','is_open','amount','tax_amount','tax_billing_line_id','tax_line_amount','daily_rate_override','default_daily_rate_snapshot','tax_rate_snapshot','is_taxable_snapshot','tax_rate_source_snapshot','warranty_provider_id','default_covered_days_snapshot','covered_days_override','extended_from_billing_line_id']
function parseSegment(v:unknown):v is Segment { if(!isObject(v)||!exact(v,segmentKeys)||!strings(v,['billing_line_id','line_type'])||!nullableStrings(v,['vehicle_id','vehicle_event_id','contract_period_id','pay_type_rule_id','pay_type','source_rule','start_time','end_time','paid_through_at','tax_billing_line_id','tax_line_amount','daily_rate_override','default_daily_rate_snapshot','tax_rate_snapshot','tax_rate_source_snapshot','warranty_provider_id','extended_from_billing_line_id'])||!money(v.amount)||!money(v.tax_amount)||typeof v.is_open!=='boolean')return false; return (v.is_taxable_snapshot===null||typeof v.is_taxable_snapshot==='boolean')&&nullableNumber(v.default_covered_days_snapshot)&&nullableNumber(v.covered_days_override) }
const warrantyKeys=['case_id','provider_id','provider_name','default_covered_days_snapshot','approved_days','effective_covered_days','default_daily_rate_snapshot','coverage_started_at','coverage_exhausted_at','current_contract_day','post_coverage_pay_type_rule_id','requires_manual_review','can_override']
function parseWarranty(v:unknown):v is ExtendedWarranty|null { return v===null||(isObject(v)&&exact(v,warrantyKeys)&&isString(v.case_id)&&nullableStrings(v,['provider_id','provider_name','default_daily_rate_snapshot','coverage_started_at','coverage_exhausted_at','post_coverage_pay_type_rule_id'])&&['default_covered_days_snapshot','approved_days','effective_covered_days','current_contract_day'].every(k=>nullableNumber(v[k]))&&typeof v.requires_manual_review==='boolean'&&typeof v.can_override==='boolean') }
const customerKeys=['customer_id','tekion_customer_number','name','phone','email']
const vehicleKeys=['vehicle_id','vin','vin_last8','stock_number','model_year','model','trim','fleet_type','current_tag']
const readyKeys=['status','transportation_event_id','transportation_event_status','reservation_id','reservation_status','reservation_type','customer','vehicle','vehicle_event_id','contract_period_id','vehicle_out_at','contract_out_at','expected_return_at','actual_return_at','billed_through_at','current_billing_line_id','line_type','pay_type_rule_id','pay_type','vehicle_class','billing_start','preview_end','effective_at','contract_days','daily_rate','rate_source','subtotal','is_taxable','tax_rate','tax_amount','tax_rate_source','tax_explanation','total','historical_subtotal','historical_tax','accumulated_subtotal','accumulated_tax','accumulated_total','segments','extended_warranty']
function parseReady(v:Record<string,unknown>):v is ReadyPreview { const c=v.customer,x=v.vehicle; return exact(v,readyKeys)&&v.status==='billing_preview_ready'&&strings(v,['transportation_event_id','transportation_event_status','reservation_id','reservation_status','reservation_type','vehicle_event_id','contract_period_id','vehicle_out_at','contract_out_at','pay_type_rule_id','pay_type','billing_start','preview_end','effective_at','rate_source'])&&nullableStrings(v,['expected_return_at','actual_return_at','billed_through_at','current_billing_line_id','line_type','vehicle_class','tax_rate_source','tax_explanation'])&&number(v.contract_days)&&['daily_rate','subtotal','tax_rate','tax_amount','total','historical_subtotal','historical_tax','accumulated_subtotal','accumulated_tax','accumulated_total'].every(k=>money(v[k]))&&typeof v.is_taxable==='boolean'&&isObject(c)&&exact(c,customerKeys)&&nullableStrings(c,customerKeys)&&isObject(x)&&exact(x,vehicleKeys)&&nullableStrings(x,vehicleKeys.filter(k=>k!=='model_year'))&&nullableNumber(x.model_year)&&Array.isArray(v.segments)&&v.segments.every(parseSegment)&&parseWarranty(v.extended_warranty) }
function parseAttention(v:Record<string,unknown>):v is AttentionPreview { if(!['billing_preview_missing_dependency','billing_preview_missing_configuration','billing_preview_unavailable'].includes(String(v.status))||!isString(v.transportation_event_id)||!isString(v.effective_at))return false; if(v.status==='billing_preview_missing_dependency')return isString(v.missing_dependency)&&v.missing_configuration===undefined; if(v.status==='billing_preview_missing_configuration')return isString(v.missing_configuration)&&v.missing_dependency===undefined; return v.missing_dependency===undefined&&v.missing_configuration===undefined }
const reservationKeys=['reservation_id','status','reservation_type','requested_model','pay_type','start_date','expected_return_datetime','actual_return_datetime','billed_through_datetime']
const currentVehicleKeys=['vehicle_event_id','vehicle_id','vin','vin_last8','stock_number','model_year','model','trim','fleet_type','current_tag','actual_out_at','actual_in_at','current_vehicle_contract_day']
const itemKeys=['transportation_event_id','transportation_event_status','source_type','source_id','expected_return_at','reservation','customer','current_vehicle','preview']
function parseItem(v:unknown):v is WorkspaceItem { if(!isObject(v)||!exact(v,itemKeys)||!strings(v,['transportation_event_id','transportation_event_status'])||!nullableStrings(v,['source_type','source_id','expected_return_at']))return false; const r=v.reservation,c=v.customer,x=v.current_vehicle,p=v.preview; return isObject(r)&&exact(r,reservationKeys)&&nullableStrings(r,reservationKeys)&&isObject(c)&&exact(c,customerKeys)&&nullableStrings(c,customerKeys)&&isObject(x)&&exact(x,currentVehicleKeys)&&nullableStrings(x,currentVehicleKeys.filter(k=>!['model_year','current_vehicle_contract_day'].includes(k)))&&nullableNumber(x.model_year)&&nullableNumber(x.current_vehicle_contract_day)&&isObject(p)&&(p.status==='billing_preview_ready'?parseReady(p):parseAttention(p)) }
function parseWorkspace(v:unknown):Workspace|null { const keys=['status','effective_at','case_count','ready_count','attention_count','accumulated_subtotal','accumulated_tax','accumulated_total','items']; if(!isObject(v)||!exact(v,keys)||v.status!=='billing_workspace_ready'||!isString(v.effective_at)||!number(v.case_count)||!number(v.ready_count)||!number(v.attention_count)||!money(v.accumulated_subtotal)||!money(v.accumulated_tax)||!money(v.accumulated_total)||!Array.isArray(v.items)||!v.items.every(parseItem)||v.case_count!==v.items.length||(v.ready_count as number)+(v.attention_count as number)!==v.case_count)return null; return v as Workspace }
const showDate=(v:string|null)=>v?new Date(v).toLocaleString():'—'
const label=(v:string)=>v.replaceAll('_',' ')
export function BillingWorkspace(){
 const [state,setState]=useState<Workspace|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[selected,setSelected]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setFailed(false);const result=await supabase.rpc('get_billing_workspace_state',{p_effective_at:new Date().toISOString()});const parsed=result.error?null:parseWorkspace(result.data);setState(parsed);setFailed(!parsed);setLoading(false)},[])
 useEffect(()=>{void load()},[load]); const detail=state?.items.find(i=>i.transportation_event_id===selected&&i.preview.status==='billing_preview_ready')
 return <main className="content billing-workspace"><section className="billing-heading"><div><p className="eyebrow">OPERATIONS / BILLING</p><h1>Billing Dashboard</h1><p>Authoritative, read-only vehicle billing state.</p></div><button type="button" className="primary-action" disabled={loading} onClick={()=>void load()}>Refresh</button></section>
 {loading&&<div className="data-message" role="status">Loading authoritative billing state…</div>}{failed&&<div className="data-message error-message" role="alert">Billing state could not be loaded. Confirm your active account and AAL2 authentication, then try again.</div>}
 {state&&<><section className="billing-metrics" aria-label="Billing summary">{[['Active cases',String(state.case_count)],['Ready cases',String(state.ready_count)],['Attention required',String(state.attention_count)],['Vehicle charges',state.accumulated_subtotal],['Separate tax',state.accumulated_tax],['Combined total',state.accumulated_total]].map(([k,v])=><div className="metric-card" key={k}><span>{k}</span><strong>{k.includes('cases')||k==='Attention required'?v:`$${v}`}</strong></div>)}</section>
 {state.case_count===0?<section className="billing-empty"><h2>No active transportation cases</h2><p>The workspace is current as of {showDate(state.effective_at)}.</p></section>:<section className="billing-cases">{state.items.map(item=>{const p=item.preview,attention=p.status!=='billing_preview_ready';return <article className={`billing-case${attention?' attention':''}`} key={item.transportation_event_id}><header><div><h2>{item.customer.name??'Customer unavailable'}</h2><p>Tekion #{item.customer.tekion_customer_number??'—'} · {item.current_vehicle.model??'Vehicle unavailable'}</p></div>{!attention&&<button type="button" className="secondary-action" onClick={()=>setSelected(selected===item.transportation_event_id?null:item.transportation_event_id)}>{selected===item.transportation_event_id?'Hide details':'View details'}</button>}</header><dl className="billing-fields"><div><dt>Reservation</dt><dd>{item.reservation.reservation_id??'—'} · {item.reservation.status??'—'}</dd></div><div><dt>VIN / stock / tag</dt><dd>{item.current_vehicle.vin??'—'} / {item.current_vehicle.stock_number??'—'} / {item.current_vehicle.current_tag??'—'}</dd></div><div><dt>Requested model/class</dt><dd>{item.reservation.requested_model??'—'}</dd></div><div><dt>Pay type</dt><dd>{item.reservation.pay_type??'—'}</dd></div><div><dt>Days in current vehicle</dt><dd>{item.current_vehicle.current_vehicle_contract_day??'—'}</dd></div><div><dt>Vehicle out</dt><dd>{showDate(item.current_vehicle.actual_out_at)}</dd></div><div><dt>Expected return</dt><dd>{showDate(item.expected_return_at)}</dd></div>{attention?<div><dt>Attention</dt><dd>{p.status==='billing_preview_missing_dependency'?label(p.missing_dependency??'unknown dependency'):p.status==='billing_preview_missing_configuration'?label(p.missing_configuration??'unknown configuration'):'Billing preview unavailable'}</dd></div>:<><div><dt>Rate source</dt><dd>{label(p.rate_source)}</dd></div><div><dt>Daily rate</dt><dd>${p.daily_rate}</dd></div><div><dt>Subtotal</dt><dd>${p.subtotal}</dd></div><div><dt>Separate tax</dt><dd>${p.tax_amount}</dd></div><div><dt>Total</dt><dd>${p.total}</dd></div></>}</dl></article>})}</section>}
 {detail&&detail.preview.status==='billing_preview_ready'&&<section className="billing-details"><h2>Billing segments &amp; Extended Warranty</h2><div className="warranty-state"><strong>Extended Warranty:</strong> {detail.preview.extended_warranty?`${detail.preview.extended_warranty.provider_name??'Configured'} · ${detail.preview.extended_warranty.effective_covered_days??'—'} effective covered days · ${detail.preview.extended_warranty.requires_manual_review?'manual review required':'no manual review'} · ${detail.preview.extended_warranty.can_override?'override permitted':'override not permitted'}`:'Not configured'}</div><div className="table-wrap"><table><thead><tr><th>Type</th><th>Period</th><th>Amount</th><th>Tax amount</th><th>Tax line amount</th></tr></thead><tbody>{detail.preview.segments.map((s,i)=><tr key={s.billing_line_id??String(i)}><td>{label(s.line_type)}</td><td>{showDate(s.start_time)} – {showDate(s.end_time)}</td><td>${s.amount}</td><td>${s.tax_amount}</td><td>{s.tax_line_amount===null?'—':`$${s.tax_line_amount}`}</td></tr>)}</tbody></table></div></section>}</>}</main>
}
