import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'

type Row={transportation_event_id:string;reservation_id:string;identifier:string;reservation_type:string;contract_out_at:string;expected_return_at:string|null;billed_through_at:string|null;pay_type:string|null;daily_rate:string|null;contract_days:number|null;amount:string|null;tax:string|null;state:'eligible'|'later'|'exact'|'rental'|'attention';reason:string|null;selectable:boolean}
type Line={id:string;ro_number:string;days:number;amount:string;tax:string;note:string|null;checked:boolean}
type Failure={transportation_event_id:string;identifier:string;reason:string}
type Batch={batch_id:string;target_at:string;created_at:string;status:string;failures:Failure[];helper_lines:Line[]}
type PipWindow=Window&{close:()=>void}
type PipApi={requestWindow:(options?:{width?:number;height?:number})=>Promise<PipWindow>}
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const local=(v:string|null)=>v?new Date(v).toLocaleString():'Unavailable'
const money=(v:string|null)=>v===null?'—':`$${v}`
function dealershipWallTimeToIso(value:string){const [date,time]=value.split('T');const [year,month,day]=date.split('-').map(Number),[hour,minute]=time.split(':').map(Number);const desired=Date.UTC(year,month-1,day,hour,minute);let candidate=desired;for(let pass=0;pass<2;pass++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(candidate));const get=(name:string)=>Number(parts.find(p=>p.type===name)?.value);const represented=Date.UTC(get('year'),get('month')-1,get('day'),get('hour'),get('minute'));candidate+=desired-represented}return new Date(candidate).toISOString()}
function upcomingSundayAtFive(now=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(now),part=(name:string)=>parts.find(p=>p.type===name)?.value??'',noon=new Date(`${part('year')}-${part('month')}-${part('day')}T12:00:00Z`),weekday=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(part('weekday'));noon.setUTCDate(noon.getUTCDate()+((7-weekday)%7));return `${noon.getUTCFullYear()}-${String(noon.getUTCMonth()+1).padStart(2,'0')}-${String(noon.getUTCDate()).padStart(2,'0')}T17:00`}

export function BulkUpdating({onApplied}:{onApplied:()=>Promise<unknown>}){
 const [target,setTarget]=useState(''),[rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<string[]>([]),[helper,setHelper]=useState<Line[]>([]),[failures,setFailures]=useState<Failure[]>([]),[batches,setBatches]=useState<Batch[]>([]),[batchId,setBatchId]=useState(''),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false)
 const dialog=useRef<HTMLDialogElement>(null),pip=useRef<PipWindow|null>(null),helperRef=useRef(helper);helperRef.current=helper
 const preview=useCallback(async(value:string)=>{if(!value){setRows([]);setSelected([]);return}const result=await supabase.rpc('get_bulk_billing_workspace_state',{p_target_at:dealershipWallTimeToIso(value)});if(result.error||!object(result.data)||!Array.isArray(result.data.items)){setMessage('Bulk preview could not be loaded.');return}setRows(result.data.items as Row[]);setSelected([])},[])
 const recall=useCallback(async(preferredId?:string)=>{const result=await supabase.rpc('get_recent_bulk_billing_batches_state');if(!result.error&&object(result.data)&&Array.isArray(result.data.batches)){const recent=result.data.batches.filter(object) as unknown as Batch[];setBatches(recent);if(recent.length){setBatchId(old=>{const selected=recent.find(batch=>batch.batch_id===(preferredId||old))??recent[0];setHelper(selected.helper_lines??[]);setFailures(selected.failures??[]);return selected.batch_id})}else{setBatchId('');setHelper([]);setFailures([])}}},[])
 useEffect(()=>{void recall()},[recall])
 const chooseBatch=(id:string)=>{const batch=batches.find(item=>item.batch_id===id);setBatchId(id);setHelper(batch?.helper_lines??[]);setFailures(batch?.failures??[])}
 const check=useCallback(async(line:Line)=>{const next=!line.checked,result=await supabase.rpc('set_bulk_helper_line_checked_state',{p_helper_line_id:line.id,p_checked:next});if(!result.error){setHelper(old=>old.map(item=>item.id===line.id?{...item,checked:next}:item));setBatches(old=>old.map(batch=>({...batch,helper_lines:batch.helper_lines.map(item=>item.id===line.id?{...item,checked:next}:item)})))}},[])
 const renderPip=useCallback(()=>{const doc=pip.current?.document;if(!doc)return;doc.body.innerHTML='<main><h2>Tekion helper</h2><p>Always-on-top persisted checklist</p></main>';const main=doc.querySelector('main');if(!main)return;for(const line of helperRef.current){const row=doc.createElement('div'),box=doc.createElement('input');box.type='checkbox';box.checked=line.checked;box.addEventListener('change',()=>void check(line));row.append(box);for(const [label,value] of [[line.ro_number,line.ro_number],[`${line.days} days`,String(line.days)],[`$${line.amount}`,line.amount],[`Tax $${line.tax}`,line.tax]]){const button=doc.createElement('button');button.textContent=label;button.addEventListener('click',()=>void navigator.clipboard.writeText(value));row.append(button)}if(line.note){const note=doc.createElement('p');note.textContent=line.note;row.append(note)}main.append(row)}},[check])
 useEffect(()=>{renderPip()},[helper,renderPip])
 const openPip=async()=>{const api=(window as Window&{documentPictureInPicture?:PipApi}).documentPictureInPicture;if(!api){setMessage('Always-on-top Picture-in-Picture is unavailable; using the sticky helper below.');return}pip.current=await api.requestWindow({width:620,height:420});pip.current.addEventListener('pagehide',()=>{pip.current=null});renderPip()}
 const apply=async()=>{if(!target){setMessage('Bulk Billing Through is required.');return}if(!selected.length){setMessage('Select at least one RO to update.');return}setBusy(true);setMessage(null);setFailures([]);const result=await supabase.rpc('apply_bulk_billing_batch_state',{p_target_at:dealershipWallTimeToIso(target),p_transportation_event_ids:selected});if(result.error||!object(result.data)){setMessage(result.error?.message??'Bulk Updating was not accepted.');setBusy(false);return}setHelper(Array.isArray(result.data.helper_lines)?result.data.helper_lines as Line[]:[]);const failed=(Array.isArray(result.data.failures)?result.data.failures.filter(object):[]) as unknown as Failure[];setFailures(failed);if(failed.length)dialog.current?.showModal();else setMessage(`${String(result.data.success_count)} RO(s) Bulk Updated.`);await onApplied();await preview(target);await recall(typeof result.data.batch_id==='string'?result.data.batch_id:undefined);setBusy(false)}
 const missingFailures=failures.filter(f=>!rows.some(row=>row.transportation_event_id===f.transportation_event_id))
 return <section className="bulk-workbench"><header><div><h2>Bulk Updating</h2><p>Daily Tekion workbench. Rental rows are situational awareness only.</p></div><label>Bulk Billing Through<input type="datetime-local" value={target} onChange={event=>{setTarget(event.target.value);if(!event.target.value)setSelected([]);setMessage(null);void preview(event.target.value)}}/></label><button type="button" onClick={()=>{const value=upcomingSundayAtFive();setTarget(value);void preview(value)}}>Bill Thru Sunday</button><button type="button" disabled={busy} onClick={()=>void apply()}>{busy?'Applying…':'Apply selected'}</button><button type="button" disabled={busy} onClick={async()=>{setBusy(true);const result=await supabase.rpc('undo_latest_bulk_billing_batch_state');setMessage(result.error?.message??'Latest applicable Bulk batch was undone.');await onApplied();await preview(target);setBusy(false)}}>Undo latest batch</button><button type="button" onClick={()=>void recall()}>Recall batches</button></header>
 {message&&<pre role="alert" className="bulk-message">{message}</pre>}<dialog ref={dialog} className="bulk-failure-dialog"><h3>Some ROs could not be updated</h3><p>Successful ROs were applied. Review every authoritative failure:</p><ul>{failures.map(f=><li key={f.transportation_event_id}><strong>{f.identifier}</strong>: {f.reason}</li>)}</ul><button type="button" onClick={()=>dialog.current?.close()}>Close</button></dialog>
 <div className="table-wrap"><table><thead><tr><th>Select</th><th>RO / Rental</th><th>Out</th><th>Expected Return</th><th>Billed through</th><th>Pay type</th><th>Daily</th><th>Days</th><th>Amount</th><th>Tax</th><th>Status</th></tr></thead><tbody>{rows.map(row=>{const failure=failures.find(f=>f.transportation_event_id===row.transportation_event_id);return <tr className={failure?'bulk-failed':`bulk-${row.state}`} key={row.transportation_event_id}><td><input type="checkbox" aria-label={`Select ${row.identifier}`} disabled={!row.selectable} checked={selected.includes(row.transportation_event_id)} onChange={event=>setSelected(old=>event.target.checked?[...old,row.transportation_event_id]:old.filter(id=>id!==row.transportation_event_id))}/></td><td>{row.identifier}</td><td>{local(row.contract_out_at)}</td><td>{local(row.expected_return_at)}</td><td>{local(row.billed_through_at)}</td><td>{row.pay_type??'—'}</td><td>{money(row.daily_rate)}</td><td>{row.contract_days??'—'}</td><td>{money(row.amount)}</td><td>{money(row.tax)}</td><td>{failure?.reason??row.reason??row.state}</td></tr>})}{missingFailures.map(f=><tr className="bulk-failed" key={f.transportation_event_id}><td>—</td><td>{f.identifier}</td><td colSpan={8}>Failed RO is no longer in the active workspace</td><td>{f.reason}</td></tr>)}</tbody></table></div>
 {batches.length>0&&<label className="bulk-recall">Recent batch<select value={batchId} onChange={event=>chooseBatch(event.target.value)}>{batches.map(batch=><option key={batch.batch_id} value={batch.batch_id}>{local(batch.created_at)} — {batch.status}</option>)}</select></label>}
 {helper.length>0&&<aside className="tekion-helper"><header><div><h3>Tekion helper</h3><p>Persisted snapshot. Click any value to copy it.</p></div><button type="button" onClick={()=>void openPip()}>{pip.current?'Reopen always-on-top':'Open always-on-top'}</button></header>{helper.map(line=><div key={line.id}><input type="checkbox" aria-label={`Complete ${line.ro_number}`} checked={line.checked} onChange={()=>void check(line)}/>{[[line.ro_number,line.ro_number],[`${line.days} days`,String(line.days)],[`$${line.amount}`,line.amount],[`Tax $${line.tax}`,line.tax]].map(([label,value])=><button type="button" key={label} onClick={()=>void navigator.clipboard.writeText(value)}>{label}</button>)}{line.note&&<span>{line.note}</span>}</div>)}</aside>}
 </section>
}
