-- Issue #59: narrow, audited Bulk Updating persistence and secured engine wrappers.
create table public.billing_bulk_batches (
 id uuid primary key default gen_random_uuid(), actor_user_id uuid not null references public.app_users(id),
 requested_target_at timestamptz not null, created_at timestamptz not null default clock_timestamp(), applied_at timestamptz,
 undone_at timestamptz, undone_by_user_id uuid references public.app_users(id), status text not null check(status in('applied','partially_applied','failed','undone'))
);
create table public.billing_bulk_items (
 id uuid primary key default gen_random_uuid(), batch_id uuid not null references public.billing_bulk_batches(id) on delete restrict,
 transportation_event_id uuid not null references public.transportation_events(id), reservation_id uuid references public.reservations(id),
 identifier text not null, succeeded boolean not null, failure_reason text, before_reservation jsonb, before_lines jsonb,
 after_reservation jsonb, after_lines jsonb, created_at timestamptz not null default clock_timestamp(),
 unique(batch_id,transportation_event_id), check((succeeded and failure_reason is null) or (not succeeded and failure_reason is not null))
);
create table public.billing_bulk_helper_lines (
 id uuid primary key default gen_random_uuid(), batch_item_id uuid not null references public.billing_bulk_items(id) on delete restrict,
 line_order integer not null, ro_number text not null, billing_line_id uuid not null, days integer not null,
 amount numeric not null, tax numeric not null, note text, checked boolean not null default false,
 checked_at timestamptz, checked_by_user_id uuid references public.app_users(id), created_at timestamptz not null default clock_timestamp(),
 unique(batch_item_id,line_order)
);
alter table public.billing_bulk_batches enable row level security;
alter table public.billing_bulk_items enable row level security;
alter table public.billing_bulk_helper_lines enable row level security;
revoke all on table public.billing_bulk_batches,public.billing_bulk_items,public.billing_bulk_helper_lines from public,anon,authenticated;
grant select on table public.billing_bulk_batches,public.billing_bulk_items,public.billing_bulk_helper_lines to authenticated;
create policy billing_bulk_batches_read on public.billing_bulk_batches for select to authenticated using (exists(select 1 from public.app_users u join public.v_user_effective_permissions p on p.user_id=u.id and p.permission_key='billing.mark_billed_through' where u.auth_user_id=auth.uid() and u.is_active));
create policy billing_bulk_items_read on public.billing_bulk_items for select to authenticated using (exists(select 1 from public.billing_bulk_batches b where b.id=batch_id));
create policy billing_bulk_helper_read on public.billing_bulk_helper_lines for select to authenticated using (exists(select 1 from public.billing_bulk_items i where i.id=batch_item_id));

create or replace function public.bulk_billing_actor_state() returns uuid language plpgsql security definer set search_path='' as $f$ declare v uuid;begin select u.id into v from public.app_users u where u.auth_user_id=auth.uid() and u.is_active; if v is null then raise exception 'Billing action access denied' using errcode='42501';end if;if coalesce(auth.jwt()->>'aal','')<>'aal2' then raise exception 'Billing action requires AAL2' using errcode='42501';end if;if not exists(select 1 from public.v_user_effective_permissions p where p.user_id=v and p.permission_key='billing.mark_billed_through') then raise exception 'Billing permission is required' using errcode='42501';end if;return v;end;$f$;

create or replace function public.get_bulk_billing_workspace_state(p_target_at timestamptz) returns jsonb language plpgsql security definer set search_path='' as $f$
declare v_actor uuid;v_items jsonb;begin v_actor:=public.bulk_billing_actor_state();if p_target_at is null then raise exception 'Bulk Billing Through is required' using errcode='22023';end if;
 select coalesce(jsonb_agg(jsonb_build_object('transportation_event_id',r.transportation_event_id,'reservation_id',r.id,'identifier',case when lower(btrim(r.reservation_type))='rental' then 'Rental '||left(r.id::text,8) else 'RO '||coalesce(r.ro_number,'unavailable') end,'reservation_type',r.reservation_type,'contract_out_at',p->>'contract_out_at','expected_return_at',r.expected_return_datetime,'billed_through_at',r.billed_through_datetime,'pay_type',p->>'pay_type','daily_rate',p->>'daily_rate','contract_days',case when p->>'contract_days'~'^\d+$' then (p->>'contract_days')::int end,'amount',p->>'subtotal','tax',p->>'tax_amount','state',case when lower(btrim(r.reservation_type))='rental' then 'rental' when p->>'status'<>'billing_preview_ready' then 'attention' when r.billed_through_datetime>p_target_at then 'later' when r.billed_through_datetime=p_target_at then 'exact' else 'eligible' end,'reason',case when lower(btrim(r.reservation_type))='rental' then 'Rental — separate payment / Extension workflow' when p->>'status'<>'billing_preview_ready' then coalesce(p->>'missing_dependency',p->>'missing_configuration','Authoritative preview unavailable') when r.billed_through_datetime>p_target_at then 'Already billed beyond target' when r.billed_through_datetime=p_target_at then 'Already at target' else 'Ready' end,'selectable',lower(btrim(r.reservation_type))<>'rental' and p->>'status'='billing_preview_ready' and (r.billed_through_datetime is null or r.billed_through_datetime<p_target_at)) order by coalesce(r.ro_number,r.id::text)),'[]'::jsonb) into v_items
 from public.reservations r cross join lateral public.get_billing_preview_state(r.transportation_event_id,p_target_at) p where lower(r.status)='active';
 return jsonb_build_object('status','bulk_billing_workspace_ready','target_at',p_target_at,'items',v_items);end;$f$;

create or replace function public.bulk_checkpoint_one_state(p_reservation_id uuid,p_target_at timestamptz,p_batch_id uuid) returns jsonb language plpgsql security definer set search_path='' as $f$
declare r public.reservations%rowtype;l public.billing_lines%rowtype;p jsonb;t jsonb;begin
 select * into r from public.reservations where id=p_reservation_id for update;if not found then raise exception 'Reservation was not found';end if;if lower(btrim(r.reservation_type))='rental' then raise exception 'Rentals cannot be Bulk Updated';end if;if lower(r.status)<>'active' then raise exception 'Reservation is no longer active';end if;if r.billed_through_datetime is not null and p_target_at=r.billed_through_datetime then raise exception 'Reservation is already billed through the target';end if;if r.billed_through_datetime is not null and p_target_at<r.billed_through_datetime then raise exception 'Billed-through timestamp cannot move backward';end if;
 perform public.reconcile_extended_warranty_coverage_state(r.transportation_event_id,p_target_at);
 select * into l from public.billing_lines x where x.reservation_id=r.id and x.transportation_event_id=r.transportation_event_id and x.parent_billing_line_id is null and x.is_open order by x.start_time desc limit 1 for update;if not found then raise exception 'Open parent billing segment was not found';end if;
 p:=public.get_billing_preview_state(r.transportation_event_id,p_target_at);if p->>'status'<>'billing_preview_ready' then raise exception 'Authoritative checkpoint preview is not ready';end if;
 perform public.set_reservation_billed_through_state(r.id,p_target_at,'Bulk Updating batch '||p_batch_id);
 update public.billing_lines set amount=(p->>'subtotal')::numeric,tax_amount=(p->>'tax_amount')::numeric,paid_through_at=p_target_at,updated_at=clock_timestamp() where id=l.id;
 t:=public.ensure_tax_child_line_state(l.id);update public.billing_lines set paid_through_at=p_target_at,updated_at=clock_timestamp() where parent_billing_line_id=l.id and line_type='tax';
 return jsonb_build_object('billing_line_id',l.id,'preview',p,'tax_child_result',t);end;$f$;

create or replace function public.apply_bulk_billing_batch_state(p_target_at timestamptz,p_transportation_event_ids uuid[]) returns jsonb language plpgsql security definer set search_path='' as $f$
declare actor uuid;b uuid:=gen_random_uuid();te uuid;r public.reservations%rowtype;i uuid;before_r jsonb;before_l jsonb;after_r jsonb;after_l jsonb;result jsonb;reason text;successes jsonb:='[]';failures jsonb:='[]';helpers jsonb:='[]';seg jsonb;n int;begin actor:=public.bulk_billing_actor_state();if p_target_at is null then raise exception 'Bulk Billing Through is required';end if;if coalesce(array_length(p_transportation_event_ids,1),0)=0 then raise exception 'Select at least one RO to update.';end if;insert into public.billing_bulk_batches(id,actor_user_id,requested_target_at,status) values(b,actor,p_target_at,'failed');
 foreach te in array p_transportation_event_ids loop begin select * into r from public.reservations where transportation_event_id=te; if not found then raise exception 'Reservation was not found';end if;before_r:=to_jsonb(r);select coalesce(jsonb_agg(to_jsonb(l) order by l.created_at),'[]') into before_l from public.billing_lines l where l.transportation_event_id=te;result:=public.bulk_checkpoint_one_state(r.id,p_target_at,b);select to_jsonb(x) into after_r from public.reservations x where x.id=r.id;select coalesce(jsonb_agg(to_jsonb(l) order by l.created_at),'[]') into after_l from public.billing_lines l where l.transportation_event_id=te;insert into public.billing_bulk_items(batch_id,transportation_event_id,reservation_id,identifier,succeeded,before_reservation,before_lines,after_reservation,after_lines)values(b,te,r.id,coalesce(r.ro_number,r.id::text),true,before_r,before_l,after_r,after_l)returning id into i;successes:=successes||jsonb_build_array(jsonb_build_object('transportation_event_id',te,'identifier',coalesce(r.ro_number,r.id::text)));n:=0;for seg in select value from jsonb_array_elements((result->'preview'->'segments')) where value->>'line_type'<>'tax' and ((value->>'paid_through_at')::timestamptz=p_target_at or ((value->>'end_time') is not null and (value->>'end_time')::timestamptz<=p_target_at and (r.billed_through_datetime is null or (value->>'end_time')::timestamptz>r.billed_through_datetime)) loop n:=n+1;insert into public.billing_bulk_helper_lines(batch_item_id,line_order,ro_number,billing_line_id,days,amount,tax,note)values(i,n,coalesce(r.ro_number,r.id::text),(seg->>'billing_line_id')::uuid,coalesce((seg->>'contract_days')::int,0),(seg->>'amount')::numeric,(seg->>'tax_amount')::numeric,case when lower(seg->>'pay_type')='customer pay' and n>1 then 'New Customer Pay line required in Tekion' end);end loop;exception when others then reason:=sqlerrm;insert into public.billing_bulk_items(batch_id,transportation_event_id,reservation_id,identifier,succeeded,failure_reason)values(b,te,r.id,coalesce(r.ro_number,te::text),false,reason);failures:=failures||jsonb_build_array(jsonb_build_object('transportation_event_id',te,'identifier',coalesce(r.ro_number,te::text),'reason',reason));end;end loop;
 update public.billing_bulk_batches set applied_at=clock_timestamp(),status=case when jsonb_array_length(successes)=0 then 'failed' when jsonb_array_length(failures)>0 then 'partially_applied' else 'applied' end where id=b;insert into public.audit_log(entity_type,entity_id,action_type,metadata,actor_user_id)values('billing_bulk_batch',b::text,'bulk_billing_apply',jsonb_build_object('target_at',p_target_at,'success_count',jsonb_array_length(successes),'failure_count',jsonb_array_length(failures)),actor::text);select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'ro_number',h.ro_number,'days',h.days,'amount',h.amount::text,'tax',h.tax::text,'note',h.note,'checked',h.checked) order by h.created_at,h.line_order),'[]') into helpers from public.billing_bulk_helper_lines h join public.billing_bulk_items bi on bi.id=h.batch_item_id where bi.batch_id=b;return jsonb_build_object('status','bulk_billing_batch_applied','batch_id',b,'success_count',jsonb_array_length(successes),'successes',successes,'failures',failures,'helper_lines',helpers);end;$f$;

create or replace function public.get_recent_bulk_billing_batches_state() returns jsonb language plpgsql security definer set search_path='' as $f$ declare actor uuid;payload jsonb;begin actor:=public.bulk_billing_actor_state();select coalesce(jsonb_agg(jsonb_build_object('batch_id',b.id,'target_at',b.requested_target_at,'created_at',b.created_at,'status',b.status,'helper_lines',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'ro_number',h.ro_number,'days',h.days,'amount',h.amount::text,'tax',h.tax::text,'note',h.note,'checked',h.checked) order by h.line_order),'[]') from public.billing_bulk_items i join public.billing_bulk_helper_lines h on h.batch_item_id=i.id where i.batch_id=b.id)) order by b.created_at desc),'[]') into payload from (select * from public.billing_bulk_batches where actor_user_id=actor order by created_at desc limit 20)b;return jsonb_build_object('status','recent_bulk_billing_batches_ready','batches',payload);end;$f$;
create or replace function public.set_bulk_helper_line_checked_state(p_helper_line_id uuid,p_checked boolean) returns jsonb language plpgsql security definer set search_path='' as $f$ declare actor uuid;begin actor:=public.bulk_billing_actor_state();update public.billing_bulk_helper_lines set checked=p_checked,checked_at=case when p_checked then clock_timestamp() end,checked_by_user_id=case when p_checked then actor end where id=p_helper_line_id;if not found then raise exception 'Tekion helper line was not found';end if;insert into public.audit_log(entity_type,entity_id,action_type,new_value,actor_user_id)values('billing_bulk_helper_line',p_helper_line_id::text,'tekion_checkoff',p_checked::text,actor::text);return jsonb_build_object('status','bulk_helper_line_check_set','helper_line_id',p_helper_line_id,'checked',p_checked);end;$f$;
create or replace function public.undo_latest_bulk_billing_batch_state() returns jsonb language plpgsql security definer set search_path='' as $f$ declare actor uuid;b public.billing_bulk_batches%rowtype;i public.billing_bulk_items%rowtype;current_r jsonb;current_l jsonb;s jsonb;old public.billing_lines%rowtype;begin actor:=public.bulk_billing_actor_state();select * into b from public.billing_bulk_batches where status in('applied','partially_applied') order by applied_at desc limit 1 for update;if not found then raise exception 'No applicable Bulk Updating batch is available to Undo';end if;for i in select * from public.billing_bulk_items where batch_id=b.id and succeeded order by id for update loop select to_jsonb(r) into current_r from public.reservations r where r.id=i.reservation_id for update;select coalesce(jsonb_agg(to_jsonb(l) order by l.created_at),'[]') into current_l from public.billing_lines l where l.transportation_event_id=i.transportation_event_id;if current_r is distinct from i.after_reservation or current_l is distinct from i.after_lines then raise exception 'Undo refused: legitimate Billing work changed after this Bulk batch for %',i.identifier;end if;delete from public.billing_lines where transportation_event_id=i.transportation_event_id and not (id=any(array(select (x->>'id')::uuid from jsonb_array_elements(i.before_lines)x)));for s in select value from jsonb_array_elements(i.before_lines) loop old:=jsonb_populate_record(null::public.billing_lines,s);insert into public.billing_lines select old.* on conflict(id) do update set amount=excluded.amount,tax_amount=excluded.tax_amount,start_time=excluded.start_time,end_time=excluded.end_time,pay_type=excluded.pay_type,pay_type_rule_id=excluded.pay_type_rule_id,line_type=excluded.line_type,parent_billing_line_id=excluded.parent_billing_line_id,is_open=excluded.is_open,paid_through_at=excluded.paid_through_at,updated_at=excluded.updated_at;end loop;update public.reservations set billed_through_datetime=(i.before_reservation->>'billed_through_datetime')::timestamptz where id=i.reservation_id;end loop;update public.billing_bulk_batches set status='undone',undone_at=clock_timestamp(),undone_by_user_id=actor where id=b.id;insert into public.audit_log(entity_type,entity_id,action_type,metadata,actor_user_id)values('billing_bulk_batch',b.id::text,'bulk_billing_undo',jsonb_build_object('fail_closed_post_state_verified',true),actor::text);return jsonb_build_object('status','bulk_billing_batch_undone','batch_id',b.id);end;$f$;

alter function public.bulk_billing_actor_state() owner to postgres;alter function public.get_bulk_billing_workspace_state(timestamptz) owner to postgres;alter function public.bulk_checkpoint_one_state(uuid,timestamptz,uuid) owner to postgres;alter function public.apply_bulk_billing_batch_state(timestamptz,uuid[]) owner to postgres;alter function public.get_recent_bulk_billing_batches_state() owner to postgres;alter function public.set_bulk_helper_line_checked_state(uuid,boolean) owner to postgres;alter function public.undo_latest_bulk_billing_batch_state() owner to postgres;
revoke all on function public.bulk_billing_actor_state(),public.get_bulk_billing_workspace_state(timestamptz),public.bulk_checkpoint_one_state(uuid,timestamptz,uuid),public.apply_bulk_billing_batch_state(timestamptz,uuid[]),public.get_recent_bulk_billing_batches_state(),public.set_bulk_helper_line_checked_state(uuid,boolean),public.undo_latest_bulk_billing_batch_state() from public,anon,authenticated;
grant execute on function public.get_bulk_billing_workspace_state(timestamptz),public.apply_bulk_billing_batch_state(timestamptz,uuid[]),public.get_recent_bulk_billing_batches_state(),public.set_bulk_helper_line_checked_state(uuid,boolean),public.undo_latest_bulk_billing_batch_state() to authenticated;
grant execute on function public.bulk_billing_actor_state(),public.bulk_checkpoint_one_state(uuid,timestamptz,uuid) to service_role;
